### ISSUE TITLE
Redux state not updating

### ISSUE THREAD

**Issue by Abhiraj-cuchd** [meabhisingh/mernProjectEcommerce#11]
My redux state of products is not updating , the action is however dispatched and i can log it on my console but the redux toolkit shows that that state is empty. please help me with this

![image](https://user-images.githubusercontent.com/94979694/173203676-181f78d8-2dce-44c4-af87-20095451d9f9.png)

![image](https://user-images.githubusercontent.com/94979694/173203689-d849d1ae-9755-4740-9cdf-d3f4bf433056.png)

![image](https://user-images.githubusercontent.com/94979694/173203696-d2347800-2c5b-4ab6-8a09-6ed20a290057.png)

**Comment by manish6022** [comment]
Check this https://stackoverflow.com/questions/71944111/redux-createstore-is-deprecated-cannot-get-state-from-getstate-in-redux-ac
