### ISSUE TITLE
i got error in productDetails

### ISSUE THREAD

**Issue by ShivammTripathi455** [meabhisingh/mernProjectEcommerce#19]
please help
![Screenshot (1)](https://user-images.githubusercontent.com/59419247/182332732-92e8866b-209b-4396-9782-da50f043f918.png)
![Screenshot (2)](https://user-images.githubusercontent.com/59419247/182332744-821a30f6-5694-47fd-a8e1-681f976ebb18.png)

**Comment by just4uamitkumar** [comment]
Hi, 
on line no. 10,
use 
const params = useParams();
 instead of
  const { params }= useParams();
  
  Do not destructor it.
