### ISSUE TITLE
Resource not found. Invalid : _id

### ISSUE THREAD

**Issue by just4uamitkumar** [meabhisingh/mernProjectEcommerce#21]
import ReviewCard from "./ReviewCard.js";
import { useParams } from 'react-router-dom'

const ProductDetails = () => {
    const [open, setOpen] = React.useState(true);
    const { params } = useParams()
    const dispatch = useDispatch();
    useEffect(() => {
        dispatch(getProductDetails(params?.id))
    }, [dispatch, params?.id])
    const { product, loading, error } = useSelector(
        (state) => state?.productDetails
    );
    
    **I am getting error 'Resource not found. Invalid: _id when try to navigate on a product detail from home page by selecting a product.**
    
    I have already use CastError in error.js
    //Wrong Mongodb id error
    if (err.name === 'CastError') {
        const message = `Resource not found. Invalid : ${err.path}`;
        err = new ErrorHandler(message, 400)
    }

**Comment by just4uamitkumar** [comment]
I was making mistake on Reducer.

**Comment by Farhatkiani** [comment]
Can you please share what was issue. I am facing same issue and stuck for last 3 days.
