### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by ShivammTripathi455** [meabhisingh/mernProjectEcommerce#22]
I got proxy error in my project.I am at
![Screenshot (5)](https://user-images.githubusercontent.com/59419247/187189996-6eefb9b3-b37c-4896-af37-750a6cf83312.png)
taching my screenshot of error please help regard this.

**Comment by Puja-Kumari-909** [comment]
Hey, The same error I was having today. If you haven't got the solution yet then it might help. 
Change proxy to "proxy": "http://localhost:4000/". And restart the server and then client

**Comment by dream-strider** [comment]
heyy, i am getting the same error, did you get any solution, pls share if you have, thank you
