### ISSUE TITLE
backend: Cannot read properties of null (reading 'role')

### ISSUE THREAD

**Issue by satyasonu** [meabhisingh/mernProjectEcommerce#23]
https://github.com/meabhisingh/mernProjectEcommerce/blob/a7ea9c9ea2b5264d0b9c561119931a49f04833d1/backend/middleware/auth.js#L22

It seems like `req.user.role` is not working here. But I couldn't figure out exact issue. Can anyone please help me?

![image](https://user-images.githubusercontent.com/64128421/187277050-9bc0ff11-34fd-49f7-bc0d-7f6f620f6315.png)

**Comment by wajahatmasood** [comment]
const ErrorHandler = require("../utils/errorhandler");
const catchAsyncErrors = require("./catchAsyncErrors");
const jwt = require("jsonwebtoken");
const  User = require("../models/userModel");


exports.isAunthenticatedUser = catchAsyncErrors(async(req, res, next)=>{

    // what is request.cookie 
    const { token } =  req.cookies;

    if(!token)
    {
        return next(new ErrorHandler("Please Login To Access This Resource", 401));
    }

    const decodedData = jwt.verify(token, process.env.JWT_SECRET);  
    req.user = await User.findById(decodedData.id);
    next(); 

});

// authorize roles wali khani ke kon kon se cheez ko access kar sakta hy

exports.authorizeRoles = (...roles) =>{
    return(req, res, next)=>{

        // this say if role.user iss array mein nai hy than yeh if chaly
        // if hum ne waha se admin bhja hy yeh if skip hu jae ga keo ke ! ka operator laga hua hy
        // this condition only work if there is no admin <-----------
        if(!roles.includes(req.user.role)){
            // 403 mean server understand the requst but refuse it
             return next(   new ErrorHandler(`Role: ${req.user.role} is not allowed to access this resource`, 403
             ));
        }

        next();
    };
};

**Comment by IgenRahul** [comment]
@satyasonu bro there is a slight error in your code 
In function `isAuthenticatedUser()` at auth.js
### change this statement 
**-->** `req.user = await User.findById(decodedData._id);`
to 
**-->** `req.user = await User.findById(decodedData.id); `
this,

**Comment by satyasonu** [comment]
Thanks Bro @IgenRahul. That was my mistake.
