### ISSUE TITLE
Problem while using React Icons in overlay Navbar during starting of the frontend . 

### ISSUE THREAD

**Issue by divyamaggarwal12345** [meabhisingh/mernProjectEcommerce#3]
ERROR in ./node_modules/react-icons/all.js 4:0-22

The requested module './io5' contains conflicting star exports for the names 'IoLogoAndroid', 'IoLogoAngular', 'IoLogoApple', 'IoLogoBitbucket', 'IoLogoBitcoin', 'IoLogoBuffer', 'IoLogoChrome', 'IoLogoClosedCaptioning', 'IoLogoCodepen', 'IoLogoCss3', 'IoLogoDesignernews', 'IoLogoDribbble', 'IoLogoDropbox', 'IoLogoEuro', 'IoLogoFacebook', 'IoLogoFlickr', 'IoLogoFoursquare', 'IoLogoGithub', 'IoLogoGoogle', 'IoLogoHackernews', 'IoLogoHtml5', 'IoLogoInstagram', 'IoLogoIonic', 'IoLogoIonitron', 'IoLogoJavascript', 'IoLogoLinkedin', 'IoLogoMarkdown', 'IoLogoNoSmoking', 'IoLogoNodejs', 'IoLogoNpm', 'IoLogoOctocat', 'IoLogoPinterest', 'IoLogoPlaystation', 'IoLogoPython', 'IoLogoReddit', 'IoLogoRss', 'IoLogoSass', 'IoLogoSkype', 'IoLogoSlack', 'IoLogoSnapchat', 'IoLogoSteam', 'IoLogoTumblr', 'IoLogoTux', 'IoLogoTwitch', 'IoLogoTwitter', 'IoLogoUsd', 'IoLogoVimeo', 'IoLogoVk', 'IoLogoWhatsapp', 'IoLogoWindows', 'IoLogoWordpress', 'IoLogoXbox', 'IoLogoXing', 'IoLogoYahoo', 'IoLogoYen', 'IoLogoYoutube' with the previous requested module './io'

**Comment by CodeAbsolute** [comment]
I tried changing the names in the  './io5' module it worked for me.
If you want you can try it too by 
1. just open the ```node_modules``` folder 
2. search for ```react-icons``` folder
3. now search for ```io5``` named folder
![image](https://user-images.githubusercontent.com/68479079/149612526-870dd8bb-e353-4c9b-9c1c-5bd6fdf21444.png)
4. now open ```index.esm.js``` and just change the names of all functions.
5. I just changed  ```Iofunction_name to IoIofunction_name ```
6. The error is solved.
Don't know if it's the right way to solve this error but this works for me currently

**Comment by sinharohan2000** [comment]
Using a lower version of `react-icons` worked for me.

`npm install react-icons@3`

**Comment by meabhisingh** [comment]
Check out This Video.
https://youtu.be/rWUm844U7nI
