### ISSUE TITLE
Protected Route not working

### ISSUE THREAD

**Issue by Ahsan22812** [meabhisingh/mernProjectEcommerce#57]
Facing this error with the new react version. Any solution?

**Comment by nilabhjaiswal** [comment]
use npm i protected-route-react install this in your frontend after that import this npm in app.js then use this npm like this 

        <Route
          exact
          path="/account"
          element={
            <ProtectedRoute>
              <Profile />
            </ProtectedRoute>
          }
        />
        <Route
          exact
          path="/me/update"
          element={
            <ProtectedRoute>
              <UpdateProfile/>
            </ProtectedRoute>
          }
        />


this will help you i asure you

**Comment by Ahsan22812** [comment]
Thank youu

**Comment by Ahsan22812** [comment]
Thank youuu

**Comment by nilabhjaiswal** [comment]
My pleasure!
