### ISSUE TITLE
Params is not recognized,

### ISSUE THREAD

**Issue by Ahsan22812** [meabhisingh/mernProjectEcommerce#59]
This params is not recognized, how to use this with the following link tag?

return (
          <Fragment>
            <Link to={`/admin/product/${params.getValue(params.id, "id")}`}>
              <EditIcon />
            </Link>

**Comment by adit26data** [comment]
Its not getting recognised even in MyOrders.js

**Comment by adit26data** [comment]
Got it!....make it....params.row.status and params.row.id

**Comment by Ahsan22812** [comment]
Thank youu
